apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: university-chatbot
spec:
  selector:
    app: chatbot-service
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
