apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-service
  namespace: university-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-service
  template:
    metadata:
      labels:
        app: chatbot-service
    spec:
      containers:
        - name: chatbot-service
          image: ashmit7tyagi/chatbot-service:latest
          ports:
            - containerPort: 5001
